name: Challenges
version: 1.0.5
main: it.glubschiii.Challenges.Main
api-version: 1.19
load: STARTUP
authors: [ Glubschiii, Niklashere ]

commands:
  timer:
    permission: challenges.timer
  settings:
    aliases: einstellungen
    permission: challenges.settings
  backpack:
    aliases: bp
    permission: challenges.backpack
  heal:
    aliases: feed
    permission: challenges.heal
  reset:
    aliases: resetandrestart
    permission: challenges.reset
  gm:
    aliases: gamemode
    permission: challenges.gm
  allitems:
    description: with /allitems skip the player can skip the current item; with /allitems overview the players see an inventory with the current item
  info:
    aliases: [dev, developer, help]
    description: get informations about the plugin and the developer