name: Challenges
version: 1.0.5
main: it.glubschiii.Challenges.Main
api-version: 1.19
load: STARTUP
authors: [ Glubschiii, Niklashere ]

commands:
  timer:
    permission: challenges.timer
  settings:
    aliases: einstellungen
    permission: challenges.settings
  backpack:
    aliases: bp
    permission: challenges.backpack
  heal:
    aliases: feed
    permission: challenges.heal
  reset:
    permission: challenges.reset
  gm:
    aliases: gamemode
    permission: challenges.gm